### ISSUE TITLE
Linux build platform for manylinux compat

### ISSUE THREAD

**Issue by fpq473** [conda-forge/ocp-feedstock#19]
### Comment:

We have been converting OCP conda packages into manylinux wheels in https://github.com/CadQuery/ocp-build-system.  The results are on [PyPI](https://pypi.org/project/cadquery-ocp/#history) and have been useful to the cadquery community.

We are running into a compatibility issue with the 7.6.3.0 packages triggered in #12  (hamfisted debugging in https://github.com/CadQuery/ocp-build-system/pull/7#issuecomment-1377770211).  They are built on ubuntu-22.04, and we believe this is forcing the manylinux wheels to be versioned as "manylinux\_2\_34", roughly meaning that they require distros providing glibc 2.34 or later.  This is fairly restrictive (e.g. fedora 35, ubuntu 21.10, debian testing).

By contrast, the "alpha" OCP packages on the cadquery conda channel ([pipeline](https://dev.azure.com/cadquery/OCP/_build)) are built on ubuntu-18.04.  This allows manylinux wheels to be versioned as "manylinux\_2\_31", which is less restrictive (e.g. debian 11, fedora 32, ubuntu-20.04).

Is it possible to rebuild 7.6.3.0 on ubuntu 20.04 (and the compiler toolchain associated with that release) or earlier?

@jmwright

**Comment by adam-urbanczyk** [comment]
Are you sure that this is the case? From the pipeline yaml:
```
DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
```

**Comment by fpq473** [comment]
@adam-urbanczyk Thanks, I see, my mistake.

It looks like the feedstock build uses [gcc-12.2](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=630965&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=233), while the cadquery pipeline uses [gcc-9.3](https://dev.azure.com/cadquery/OCP/_build/results?buildId=2552&view=logs&j=a1fb9864-b881-5568-0b92-71e1df4c2b07&t=88fea948-9e59-5c95-844e-534ff062928e&l=58).  I think that is also consistent with the observed manylinux results.

So perhaps the question is whether gcc 9 can be used?  (Maybe it's the gxx version that matters, but I suspect the version used here is similarly newer than the version in the cadquery alpha build.)

**Comment by fpq473** [comment]
@adam-urbanczyk Or perhaps we can build 7.6.3.0 (I assume it's different from 7.6.3.alpha) in the cadquery pipeline and upload that to the cadquery channel.  But perhaps the two pipelines differ in more than where the result gets published, and the conda-forge one is preferred?

**Comment by adam-urbanczyk** [comment]
AFAIK this is the conda-forge toolchain and one has to use it for conda-forge packages to ensure compatibility.

**Comment by fpq473** [comment]
Thanks for explaining.  Closing then.
