### ISSUE TITLE
Package seems to allow environments with OCCT 7.7.1, but the bindings are incompatible.

### ISSUE THREAD

**Issue by whophil** [conda-forge/ocp-feedstock#28]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Package seems to allow environments with OCCT 7.7.1, but the bindings are incompatible.

I thought `pin_compatible('occt', max_pin='x.x.x')` would have prevented this, but it doesn't.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by adam-urbanczyk** [comment]
This is what I see in the rendered recipe:
```
  run:
    - occt >=7.7.0,<7.8.0a0
 ```
I'll try adding one more x...
