### ISSUE TITLE
C++ compiler under Windows 

### ISSUE THREAD

**Issue by bernhard-42** [conda-forge/ocp-feedstock#44]
### Comment:

What is the compiler and version used under Windows to build the OCP dynamic library?
I would need it to compile another library for use with OCP objects and ensure ABI compatibility.
I'd expect we need the same compiler as is the case with Linux (where ocp 7.7.2 is built with gxx_linux-64 version 12.*)

**Comment by bernhard-42** [comment]
I think we found it: https://github.com/conda-forge/ocp-feedstock/blob/1a6735df560209c68a06e202219cca7346b27fbd/.ci_support/win_64_python3.11.____cpython.yaml#L5

```yaml
...
cxx_compiler:
- vs2019
...
```

**Comment by whophil** [comment]
That is the right place to look @bernhard-42 . I have done this successfully on win/mac/linux, so feel free to reach out if you run into issues.
