### ISSUE TITLE
Broken after migration of occt 7.5.3 to vtk 9.1.0

### ISSUE THREAD

**Issue by whophil** [conda-forge/ocp-feedstock#7]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This package is broken after the merge of https://github.com/conda-forge/occt-feedstock/pull/82 by @looooo, which migrates OCCT 7.5.3 to VTK 9.1.0.

The latest version of this package was built with VTK 9.0.1, however it seems to be permitted to run with VTK 9.1.0. This fails at `import OCP` due to a misnamed VTK library. I'm not sure what the "proper" way to fix this is - @looooo do you have any suggestions?

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by looooo** [comment]
maybe you need to make cop dependent on vtk?
